version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    image: akharote1/educhain-blockchain:1.0.0
    build: ./blockchain
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  react:
    image: akharote1/educhain:1.0.0
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - dapp